### ISSUE TITLE
Panic case: decData.GenerateHashID fails when nil value passed in params

### ISSUE THREAD

**Issue by muku314115** [AssetMantle/modules#125] opened 2022-11-07 13:43 UTC
decData.go: passing nil value in decData.GenerateHashID leads to panic - check if this is expected behaviour or not, null checks can be added to avoid fatal panic

**Comment by 0xankit** [comment] 2022-12-08 12:05
duplicate of #164 
As explained in #164 problem is with `compare()` of decData

**Closed** 2022-12-09 08:11 UTC
